### ISSUE TITLE
https://github.com/adelphinsucasa/Capstone-Project-with-Kanban-board/projects/1

### ISSUE THREAD

**Issue by adelphinsucasa** [adelphinsucasa/Capstone-Project-with-Kanban-board#21]
Hi.

We are working on the Capstone Project
https://github.com/adelphinsucasa/Capstone-Project-with-Kanban-board/projects/1

In this team we are two code partners:

1.  Jose Delphin (Student A)
2.  Haftamu Desta (Student B)

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @adelphinsucasa, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] Kindly add a link to this repository Kanban Board Project in this issue and please make sure you assign the students to each card of the project like the project required. You should see a circle with the user's avatar on each card. See the example below:
- 
![image](https://user-images.githubusercontent.com/61919617/218586380-56573435-2692-4ac6-8771-ddb63145aff3.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by adelphinsucasa** [comment]
Thank you, Now we have assigned each activity.

**Comment by Munsa1** [comment]
Hi @adelphinsucasa @haftamudesta , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
N/A

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
